# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patentanalysis', '0002_pubcolrel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('path', models.TextField(max_length=500)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patentanalysis.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patentanalysis.Collection')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patentanalysis.Publication')),
            ],
        ),
    ]
