# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patentanalysis', '0003_model_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='field_analyze',
            field=models.CharField(default='title_dwpi', max_length=100),
            preserve_default=False,
        ),
    ]
