# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patentanalysis', '0006_chemicalphrase_collectionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalphrase',
            name='source',
            field=models.CharField(default='native', max_length=100),
            preserve_default=False,
        ),
    ]
